version: "2.14.0"

services:
  mysql:
    image: "mysql:8-oracle"
    container_name: mysql
    ports:
      - 3306:3306
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_DATABASE=pizza_shop
      - MYSQL_USER=dummyuser
      - MYSQL_PASSWORD=dummypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/1.sql"